### ISSUE TITLE
moveit_cfgs: can't load existing MoveIt configs into Setup Assistant

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/fanuc#217]
As per subject.

Loading any of the top-level xacros into the Setup Assistant under Indigo results in:

```
[1495480044.940728529] [ INFO] [/moveit_setup_assistant] [ros.moveit_setup_assistant]: Running 'rosrun xacro xacro.py /home/user/catkin_ws/src/fanuc/fanuc_m10ia_support/urdf/m10ia.xacro'...
Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  ...
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 369, in eval_lit
    raise XacroException("Property wasn't defined: %s" % str(ex))
xacro.XacroException: Property wasn't defined: u'pi'
```

It looks like the MSA doesn't use `--in-order` on Indigo and thus doesn't use Jade+ xacro processing.

**Comment by gavanderhoorn** [comment]
Ref: ros-planning/moveit#511.
